#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 16 04:45:29 2017

@author: apple
"""

import numpy as np
import matplotlib.pyplot as plt

image=plt.imread("lena.png")
inv_image=1-image
bin_image=np.array(image>image.mean(),dtype=int)

transpose_image=np.copy(image)
transpose_image[:,:,0]=image[:,:,0].T
transpose_image[:,:,1]=image[:,:,1].T
transpose_image[:,:,2]=image[:,:,2].T
print(image.min(),image.max())


plt.subplot(231)
plt.title("Original")
plt.imshow(image)
plt.subplot(232)
plt.title("Inverse")
plt.imshow(inv_image)
plt.subplot(233)
plt.title("Transpose")
plt.imshow(transpose_image)
plt.subplot(234)
plt.imshow(bin_image[:,:,0])
plt.subplot(235)
plt.imshow(bin_image[:,:,1])
plt.subplot(236)
plt.imshow(bin_image[:,:,2])



